[tox]
envlist =
    tests
    linting
    coverage
    type_check
skip_missing_interpreters = True
skipsdist = True

[testenv]
commands = python -m pip install --upgrade pip

[testenv:tests]
deps =
    -r requirements.txt
    .[tests]
setenv = PYTHONPATH = {toxinidir}/src
commands = python -m pytest --basetemp={envtmpdir} {posargs}

[testenv:linting]
deps =
    {[testenv:tests]deps}
    .[linting]
setenv = PYTHONPATH = {toxinidir}/src
commands =
    pylint tmds_mcp
    pylint unittests --rcfile=unittests/.pylintrc

[testenv:type_check]
setenv = PYTHONPATH = {toxinidir}/src
deps =
    {[testenv:tests]deps}
    .[type_check]
commands =
    mypy --show-error-codes src/tmds_mcp --strict
    mypy --show-error-codes unittests --strict

[testenv:spell_check]
setenv = PYTHONPATH = {toxinidir}/src
deps =
    -r requirements.txt
    .[spell_check]
commands =
    codespell --ignore-words=domain-specific-terms.txt src
    codespell --ignore-words=domain-specific-terms.txt README.md

[testenv:formatting]
# the formatting environment checks that black and isort have been applied
deps =
    .[formatting]
commands =
    black . --check
    isort . --check

[testenv:coverage]
changedir = unittests
deps =
    {[testenv:tests]deps}
    .[coverage]
setenv = PYTHONPATH = {toxinidir}/src
commands =
    coverage run -m pytest --basetemp={envtmpdir} {posargs}
    coverage html --omit .tox/*,unittests/*
    coverage report --fail-under 80 --omit .tox/*,unittests/*

[testenv:compile_requirements]
deps =
    pip-tools
commands =
    pip-compile pyproject.toml

[testenv:dev]
deps =
    {[testenv:tests]deps}
    {[testenv:linting]deps}
    {[testenv:type_check]deps}
    {[testenv:coverage]deps}
    {[testenv:spell_check]deps}
    .[formatting]
    .[dev]
commands =
    python -m pip install --upgrade pip
    pip install -r requirements.txt

[testenv:test_packaging]
skip_install = true
deps =
    .[packaging]
commands =
    python -m build
    twine check dist/*
