name: Upload Python Package

on:
  release:
    types: [created, edited]

jobs:
  tests:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.14"]
        os: [ubuntu-latest]
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run the Unit Tests
        run: uv run --group tests pytest
      - name: Run linting
        run: |
          uv run --locked --group linting ruff check .
      - name: Run type_check
        run: |
          uv run --group type_check mypy --show-error-codes src/tmds_mcp --strict
          uv run --group type_check mypy --show-error-codes unittests --strict
      - name: Run Tests and Record Coverage
        run: |
          uv run --group coverage coverage run -m pytest
          uv run --group coverage coverage html --omit "unittests/*"
          uv run --group coverage coverage report --fail-under 80 --omit "unittests/*"

  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.14" ]
        os: [ ubuntu-latest ]
    environment: release
    permissions:
        id-token: write
    needs: tests
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheel and source distributions
        run: uv build
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
